cache:
  mount:
    - /drone/sundials-3.2.1

build:
  image: bjodah/bjodahimg16dev:v1.6
  environment:
    - OMP_NUM_THREADS=1
    - ANYODE_NUM_THREADS=2
    - CPLUS_INCLUDE_PATH=/opt/boost_1_69_0/include:/drone/sundials-3.2.1/include
    - LIBRARY_PATH=/opt/boost_1_69_0/lib:/drone/sundials-3.2.1/lib
    - LD_LIBRARY_PATH=/opt/boost_1_69_0/lib:/drone/sundials-3.2.1/lib
  commands:
    - if [ ! -d /drone/sundials-3.2.1 ]; then .ci/get_sundials.sh 3.2.1 /drone/sundials-3.2.1 -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_SIZE=32; fi
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh pyodesys
    - ./scripts/prepare_deploy.sh
    - .ci/test_py2.sh pyodesys /drone/sund-3.2.1-klu
    - rm -r ~/.cache/python*pyodesys*/
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda upgrade conda-build
    - PATH=/opt/miniconda3/bin:$PATH conda-build conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh
    - ./scripts/grep-for-binary-data.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
