clone:
   default:
     image: plugins/git
     recursive: true
     submodule_override:
       external/anyode: git://github.com/bjodah/anyode.git

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./ci_cache/sund-3.2.1-klu
      - ./ci_cache/sund-4.1.0-nolapack-noklu-extended
      - ./ci_cache/conda_packages
      - ./ci_cache/pip_cache
    volumes:
      - /tmp/cache:/cache
    ttl: 90  # liftetime in days

  test-sund-3.2.1-klu:
    group: testing
    image: bjodah/bjodahimg18:v1.5
    environment:
      - OMP_NUM_THREADS=1
      - ANYODE_NUM_THREADS=2
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      - export SUNDBASE=$(pwd)/ci_cache/sund-3.2.1-klu
      - if [ ! -d $SUNDBASE ]; then .ci/get_sundials.sh 3.2.1 $SUNDBASE -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_SIZE=32 -DKLU_ENABLE:BOOL=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; fi
      - mkdir -p $HOME/.config/pip/; bash -c 'echo -e "[global]\nno-cache-dir = false\ndownload-cache = $(pwd)/ci_cache/pip_cache" >$HOME/.config/pip/pip.conf'
      - bash -c "ulimit -v 2048000; .ci/run_ci.sh pyodesys $SUNDBASE"
      - ./scripts/prepare_deploy.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - ./scripts/grep-for-merge-blocking-token.sh
      - ./scripts/grep-for-binary-data.sh
      
  test-sund-4.1.0-nolapack-noklu-extended:
    group: testing
    image: bjodah/bjodahimg18:v1.5
    environment:
      - OMP_NUM_THREADS=1
      - ANYODE_NUM_THREADS=2
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      - export SUNDBASE=$(pwd)/ci_cache/sund-4.1.0-nolapack-noklu-extended
      - if [ ! -d $SUNDBASE ]; then .ci/get_sundials.sh 4.1.0 $SUNDBASE -DLAPACK_ENABLE:BOOL=OFF -DSUNDIALS_INDEX_SIZE=32 -DSUNDIALS_PRECISION:STRING="extended" -DKLU_ENABLE:BOOL=OFF; fi
      # Need to install pycvodes from source for extended precision/int64 test, since
      # that requires no LAPACK, whereas the pypi version installs with LAPACK
      - git clone --recurse-submodules https://github.com/bjodah/pycvodes.git /tmp/pycvodes
      - cd /tmp/pycvodes
      - LIBRARY_PATH=$SUNDBASE/lib:$LIBRARY_PATH CPATH=$SUNDBASE/include:$CPATH LD_LIBRARY_PATH=$SUNDBASE/lib:$LD_LIBRARY_PATH PYCVODES_LAPACK=0 PYCVODES_NO_KLU=1 python3 setup.py install
      - cd -
      - mkdir -p $HOME/.config/pip/; bash -c 'echo -e "[global]\nno-cache-dir = false\ndownload-cache = $(pwd)/ci_cache/pip_cache" >$HOME/.config/pip/pip.conf'
      - bash -c "ulimit -v 2048000; .ci/run_ci.sh pyodesys $SUNDBASE"

  test-conda-recipe:
    group: testing
    image: bjodah/bjodahimg18dev:v1.5
    commands:
      - export CONDA_PKGS_DIRS=$(pwd)/ci_cache/conda_packages
      - PATH=/opt/miniconda3/bin:$PATH conda build  --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe

  test-py2:
    image: bjodah/bjodahimg18:v1.5
    environment:
      - OMP_NUM_THREADS=1
      - ANYODE_NUM_THREADS=2
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      - export SUNDBASE=$(pwd)/ci_cache/sund-3.2.1-klu
      - bash -c "ulimit -v 2048000; .ci/test_py2.sh pyodesys $SUNDBASE"

deploy:

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./ci_cache/sund-3.2.1-klu
      - ./ci_cache/sund-4.1.0-nolapack-noklu-extended
      - ./ci_cache/conda_packages
      - ./ci_cache/pip_cache
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: pyodesys
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
