build:
  image: bjodah/bjodahimg16dev:v1.3
  environment:
    - OMP_NUM_THREADS=1
    - ANYODE_NUM_THREADS=2
    - CPLUS_INCLUDE_PATH=/opt/boost_1_65_0/include:/usr/include/suitesparse
    - LIBRARY_PATH=/opt/boost_1_65_0/lib
    - LD_LIBRARY_PATH=/opt/boost_1_65_0/lib
  commands:
    - apt-get update --quiet && apt-get install --quiet -y libsuitesparse-dev
    - python2 -m pip install --ignore-installed --no-deps quantities==0.12.1  # https://github.com/python-quantities/python-quantities/issues/122
    - python3 -m pip install --ignore-installed --no-deps quantities==0.12.1
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh pyodesys
    - ./scripts/prepare_deploy.sh
    - rm -r ~/.cache/python*pyodesys*/
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda upgrade conda-build
    - PATH=/opt/miniconda3/bin:$PATH conda-build conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh
    - ./scripts/grep-for-binary-data.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodesys
    source: deploy/
    target: ~
    recursive: true
    delete: false
