clone:
   default:
     image: plugins/git
     recursive: true
     submodule_override:
       external/anyode: git://github.com/bjodah/anyode.git

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./ci_cache/conda_packages
      - ./ci_cache/pip_cache
    volumes:
      - /tmp/cache:/cache
    ttl: 90  # liftetime in days

  # get-pre-reqs:
  #   image: bjodah/bjodahimg20dev:21.7.b
  #   commands:
  #     - mkdir ./tmp
  #     - git clone --recurse-submodules https://github.com/bjodah/pycvodes.git ./tmp/pycvodes

  # test-py2:
  #   image: bjodah/bjodahimg20dev:21.7.b
  #   environment:
  #     - CC=gcc-10
  #     - CXX=g++-10
  #     - OMP_NUM_THREADS=1
  #     - ANYODE_NUM_THREADS=2
  #     - CPLUS_INCLUDE_PATH=/usr/include/suitesparse:/opt/boost-1.76.0/include
  #     - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
  #     - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
  #     - SUNDBASE=/opt/sundials-5.7.0-release
  #   commands:
  #     - apt-get update && apt-get --assume-yes install python2-dev
  #     - bash -c "ulimit -v 2048000; .ci/test_py2.sh pyodesys $SUNDBASE"

  test-sund-5.4.0-klu:
    group: testing
    image: bjodah/bjodahimg20dot:21.7.b
    environment:
      - CC=gcc-10
      - CXX=g++-10
      - OMP_NUM_THREADS=1
      - ANYODE_NUM_THREADS=2
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse:/opt/boost-1.76.0/include
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - SUNDBASE=/opt/sundials-5.7.0-release
    commands:
      - bash -c "ulimit -v 2048000; .ci/run_ci.sh pyodesys $SUNDBASE"
      - ./scripts/prepare_deploy.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      
  test-sund-5.4.0-nolapack-noklu-extended:
    group: testing
    image: bjodah/bjodahimg20dot:21.7.b
    environment:
      - CC=gcc-10
      - CXX=g++-10
      - OMP_NUM_THREADS=1
      - ANYODE_NUM_THREADS=2
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse:/opt/boost-1.76.0/include
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - SUNDBASE=/opt/sundials-5.4.0-noklu-nolapack-extended-int64
      - PYCVODES_NO_LAPACK=1
      - PYCVODES_NO_KLU=1
    commands:
      - bash -c "ulimit -v 2048000; .ci/run_ci.sh pyodesys $SUNDBASE"
      - git clean -xfd
      - ./scripts/grep-for-merge-blocking-token.sh
      - ./scripts/grep-for-binary-data.sh

deploy:

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./ci_cache/conda_packages
      - ./ci_cache/pip_cache
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: pyodesys
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
