{% set name = "pyodesys" %}
{% set version = "0.13.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - numpy
    - sym >=0.3.4
    - sympy >=1.1.1,!=1.2
    - scipy
    - matplotlib
    - appdirs
    - boost
    - pyodeint >=0.10.1
    - pygslodeiv2 >=0.9.1
    - pycvodes >=0.11.12
    - pycompilation >=0.4.9
    - pycodeexport >=0.1.2
    - cython
    - python-symengine
#    - symcxx
#    - pysym
    - matplotlib >=2.0.2
    - gxx_linux-64


test:
  imports:
    - {{ name }}
  requires:
    - pytest -x


about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Straightforward numerical integration of systems of ordinary differential equations'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
