{% set name = "pyodesys" %}
{% set version = "0.12.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - sym
    - sympy
    - scipy
    - matplotlib
    - appdirs
    - boost
    - pyodeint >=0.9.4
    - pygslodeiv2 >=0.8.4
    - pycvodes >=0.10.5
    - pycompilation
    - pycodeexport
    - python-symengine
    - symcxx
    - pysym
    - matplotlib >=2.0.2

test:
  imports:
    - {{ name }}
  requires:
    - pytest


about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Straightforward numerical integration of systems of ordinary differential equations'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
