{% set name = "pyodesys" %}
{% set version = GIT_DESCRIBE_TAG | replace("v", "") %}
{% set number = GIT_DESCRIBE_NUMBER | int %}
{% if number > 0 %}
   {% set version = version + ".post" + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG | replace("v", "") }}{% if number > 0 %}.post{{ GIT_DESCRIBE_NUMBER }}{% endif %}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - sym >=0.3.4
    - sympy >=1.1.1,!=1.2
    - scipy
    - matplotlib
    - appdirs
    - boost
    - pyodeint >=0.10.1
    - pygslodeiv2 >=0.9.1
    - pycvodes >=0.11.9
    - pycompilation
    - pycodeexport >=0.1.2
    - cython
    - python-symengine
    - symcxx
    - pysym
    - matplotlib >=2.0.2

test:
  imports:
    - {{ name }}
  requires:
    - pytest


about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Straightforward numerical integration of systems of ordinary differential equations'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
